author:  Ryan Fisher
tagline: Software Engineer, Hobbyist Photographer, Couch Philosopher
meta_description: Ryan Fisher is a software engineer based in San Diego, Ca. He spends most of his time sitting quietly, writing code, and soaking in compliments about his beard.

highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ryan Fisher"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      author: "Ryan Fisher"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"


analytics:
  google:
    id:    UA-20742253-1

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

assets:
  js_compressor: uglifier
  css_compressor: sass
